"""
Complete fix for Notebook 3: Add all missing components to work with PCA features.

This adds:
1. PCA features loading from Notebook 2 output
2. FeatureDataset class
3. BrainTumorClassifier for PCA features
4. train_model function
"""

import json
from pathlib import Path

NOTEBOOK_PATH = Path("3_semi_supervised_learning.ipynb")

with open(NOTEBOOK_PATH, 'r', encoding='utf-8') as f:
    nb = json.load(f)

print(f"Current cells: {len(nb['cells'])}")

# ============================================================================
# NEW CELL: Load PCA Features
# ============================================================================
load_pca_cell = {
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Load PCA features generated by Notebook 2\n",
        "print(\"=\"*60)\n",
        "print(\"LOADING PCA FEATURES FROM NOTEBOOK 2\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "# Load ALL PCA features (combined: train+val+test+unlabeled)\n",
        "features_pca_50 = np.load(FEATURES_DIR / 'features_pca_50.npy')\n",
        "print(f\"\\nTotal PCA features loaded: {features_pca_50.shape}\")\n",
        "\n",
        "# Split PCA features according to weak_labels_df splits\n",
        "# weak_labels_df has 'split' column: 'train', 'val', 'test', 'unlabeled'\n",
        "\n",
        "train_mask = weak_labels_df['split'] == 'train'\n",
        "val_mask = weak_labels_df['split'] == 'val'\n",
        "test_mask = weak_labels_df['split'] == 'test'\n",
        "unlabeled_mask = weak_labels_df['split'] == 'unlabeled'\n",
        "\n",
        "train_pca = features_pca_50[train_mask]\n",
        "val_pca = features_pca_50[val_mask]\n",
        "test_pca = features_pca_50[test_mask]\n",
        "unlabeled_pca = features_pca_50[unlabeled_mask]\n",
        "\n",
        "# Get labels\n",
        "train_labels = weak_labels_df[train_mask]['true_label'].values\n",
        "val_labels = weak_labels_df[val_mask]['true_label'].values\n",
        "test_labels = weak_labels_df[test_mask]['true_label'].values\n",
        "\n",
        "# Combine train+val for cross-validation\n",
        "all_labeled_pca = np.vstack([train_pca, val_pca])\n",
        "all_labeled_labels = np.hstack([train_labels, val_labels])\n",
        "\n",
        "print(f\"\\nPCA Features Split:\")\n",
        "print(f\"  - Train: {train_pca.shape}\")\n",
        "print(f\"  - Val: {val_pca.shape}\")\n",
        "print(f\"  - Test: {test_pca.shape}\")\n",
        "print(f\"  - Unlabeled: {unlabeled_pca.shape}\")\n",
        "print(f\"  - All labeled (train+val): {all_labeled_pca.shape}\")\n",
        "\n",
        "print(f\"\\nLabels:\")\n",
        "print(f\"  - Train labels: {train_labels.shape} (Normal: {(train_labels==0).sum()}, Cancer: {(train_labels==1).sum()})\")\n",
        "print(f\"  - Val labels: {val_labels.shape} (Normal: {(val_labels==0).sum()}, Cancer: {(val_labels==1).sum()})\")\n",
        "print(f\"  - Test labels: {test_labels.shape} (Normal: {(test_labels==0).sum()}, Cancer: {(test_labels==1).sum()})\")\n",
        "print(f\"  - All labeled: {all_labeled_labels.shape}\")\n"
    ]
}

# ============================================================================
# NEW CELL: FeatureDataset Class
# ============================================================================
feature_dataset_cell = {
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Dataset class for PCA features\n",
        "class FeatureDataset(torch.utils.data.Dataset):\n",
        "    \"\"\"PyTorch Dataset for pre-extracted PCA features.\"\"\"\n",
        "    def __init__(self, features, labels):\n",
        "        self.features = torch.FloatTensor(features)\n",
        "        self.labels = torch.LongTensor(labels)\n",
        "    \n",
        "    def __len__(self):\n",
        "        return len(self.features)\n",
        "    \n",
        "    def __getitem__(self, idx):\n",
        "        return self.features[idx], self.labels[idx]\n",
        "\n",
        "print(\"✓ FeatureDataset class defined\")"
    ]
}

# ============================================================================
# NEW CELL: BrainTumorClassifier for PCA Features
# ============================================================================
classifier_cell = {
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Simple MLP classifier for PCA features\n",
        "class BrainTumorClassifier(nn.Module):\n",
        "    \"\"\"Multi-layer perceptron for PCA features classification.\"\"\"\n",
        "    def __init__(self, input_dim=50, hidden_dim=128, dropout=0.5):\n",
        "        super(BrainTumorClassifier, self).__init__()\n",
        "        self.fc1 = nn.Linear(input_dim, hidden_dim)\n",
        "        self.bn1 = nn.BatchNorm1d(hidden_dim)\n",
        "        self.dropout1 = nn.Dropout(dropout)\n",
        "        \n",
        "        self.fc2 = nn.Linear(hidden_dim, hidden_dim // 2)\n",
        "        self.bn2 = nn.BatchNorm1d(hidden_dim // 2)\n",
        "        self.dropout2 = nn.Dropout(dropout)\n",
        "        \n",
        "        self.fc3 = nn.Linear(hidden_dim // 2, 2)  # Binary classification\n",
        "        \n",
        "    def forward(self, x):\n",
        "        x = self.fc1(x)\n",
        "        x = self.bn1(x)\n",
        "        x = torch.relu(x)\n",
        "        x = self.dropout1(x)\n",
        "        \n",
        "        x = self.fc2(x)\n",
        "        x = self.bn2(x)\n",
        "        x = torch.relu(x)\n",
        "        x = self.dropout2(x)\n",
        "        \n",
        "        x = self.fc3(x)\n",
        "        return x\n",
        "\n",
        "print(\"✓ BrainTumorClassifier defined (MLP for PCA features)\")"
    ]
}

# ============================================================================
# NEW CELL: train_model Function
# ============================================================================
train_model_cell = {
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Training function with early stopping\n",
        "def train_model(model, train_loader, val_loader, criterion, optimizer, epochs=50, patience=10):\n",
        "    \"\"\"\n",
        "    Train model with early stopping.\n",
        "    \n",
        "    Returns:\n",
        "        model: Trained model\n",
        "        history: Training history dict\n",
        "    \"\"\"\n",
        "    best_val_loss = float('inf')\n",
        "    patience_counter = 0\n",
        "    history = {'train_loss': [], 'val_loss': [], 'val_acc': []}\n",
        "    \n",
        "    for epoch in range(epochs):\n",
        "        # Training\n",
        "        model.train()\n",
        "        train_loss = 0\n",
        "        for features, labels in train_loader:\n",
        "            features, labels = features.to(device), labels.to(device)\n",
        "            \n",
        "            optimizer.zero_grad()\n",
        "            outputs = model(features)\n",
        "            loss = criterion(outputs, labels)\n",
        "            loss.backward()\n",
        "            optimizer.step()\n",
        "            \n",
        "            train_loss += loss.item() * features.size(0)\n",
        "        \n",
        "        train_loss /= len(train_loader.dataset)\n",
        "        \n",
        "        # Validation\n",
        "        model.eval()\n",
        "        val_loss = 0\n",
        "        correct = 0\n",
        "        total = 0\n",
        "        \n",
        "        with torch.no_grad():\n",
        "            for features, labels in val_loader:\n",
        "                features, labels = features.to(device), labels.to(device)\n",
        "                outputs = model(features)\n",
        "                loss = criterion(outputs, labels)\n",
        "                val_loss += loss.item() * features.size(0)\n",
        "                \n",
        "                _, predicted = outputs.max(1)\n",
        "                total += labels.size(0)\n",
        "                correct += predicted.eq(labels).sum().item()\n",
        "        \n",
        "        val_loss /= len(val_loader.dataset)\n",
        "        val_acc = correct / total\n",
        "        \n",
        "        history['train_loss'].append(train_loss)\n",
        "        history['val_loss'].append(val_loss)\n",
        "        history['val_acc'].append(val_acc)\n",
        "        \n",
        "        # Early stopping\n",
        "        if val_loss < best_val_loss:\n",
        "            best_val_loss = val_loss\n",
        "            patience_counter = 0\n",
        "            best_model_state = model.state_dict().copy()\n",
        "        else:\n",
        "            patience_counter += 1\n",
        "        \n",
        "        if patience_counter >= patience:\n",
        "            model.load_state_dict(best_model_state)\n",
        "            break\n",
        "    \n",
        "    return model, history\n",
        "\n",
        "print(\"✓ train_model function defined\")"
    ]
}

# ============================================================================
# NEW CELL: evaluate_model Function
# ============================================================================
evaluate_model_cell = {
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        "# Evaluation function\n",
        "def evaluate_model(model, dataloader):\n",
        "    \"\"\"\n",
        "    Evaluate model and return comprehensive metrics.\n",
        "    \n",
        "    Returns:\n",
        "        metrics: Dict of metrics\n",
        "        predictions: Numpy array of predictions\n",
        "        labels: Numpy array of true labels\n",
        "        probabilities: Numpy array of probabilities\n",
        "    \"\"\"\n",
        "    model.eval()\n",
        "    all_preds = []\n",
        "    all_labels = []\n",
        "    all_probs = []\n",
        "    \n",
        "    with torch.no_grad():\n",
        "        for features, labels in dataloader:\n",
        "            features = features.to(device)\n",
        "            outputs = model(features)\n",
        "            probs = torch.softmax(outputs, dim=1)\n",
        "            _, preds = outputs.max(1)\n",
        "            \n",
        "            all_preds.extend(preds.cpu().numpy())\n",
        "            all_labels.extend(labels.numpy())\n",
        "            all_probs.extend(probs[:, 1].cpu().numpy())  # Probability of class 1\n",
        "    \n",
        "    all_preds = np.array(all_preds)\n",
        "    all_labels = np.array(all_labels)\n",
        "    all_probs = np.array(all_probs)\n",
        "    \n",
        "    # Calculate metrics\n",
        "    from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, fbeta_score\n",
        "    \n",
        "    metrics = {\n",
        "        'accuracy': accuracy_score(all_labels, all_preds),\n",
        "        'precision': precision_score(all_labels, all_preds, zero_division=0),\n",
        "        'recall': recall_score(all_labels, all_preds, zero_division=0),\n",
        "        'f1': f1_score(all_labels, all_preds, zero_division=0),\n",
        "        'f2': fbeta_score(all_labels, all_preds, beta=2, zero_division=0)\n",
        "    }\n",
        "    \n",
        "    return metrics, all_preds, all_labels, all_probs\n",
        "\n",
        "print(\"✓ evaluate_model function defined\")"
    ]
}

# ============================================================================
# Insert cells in the right order
# ============================================================================

# Insert after cell 4 (which loads weak_labels_df)
insert_position = 5

cells_to_insert = [
    load_pca_cell,
    feature_dataset_cell,
    classifier_cell,
    train_model_cell,
    evaluate_model_cell
]

print(f"\nInserting {len(cells_to_insert)} new cells at position {insert_position}")

for cell in reversed(cells_to_insert):
    nb['cells'].insert(insert_position, cell)

print(f"New total cells: {len(nb['cells'])}")

# Save notebook
with open(NOTEBOOK_PATH, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("\n" + "="*60)
print("NOTEBOOK UPDATED SUCCESSFULLY")
print("="*60)
print(f"\nAdded cells:")
print(f"  Cell {insert_position}: Load PCA features from Notebook 2")
print(f"  Cell {insert_position+1}: FeatureDataset class")
print(f"  Cell {insert_position+2}: BrainTumorClassifier (MLP)")
print(f"  Cell {insert_position+3}: train_model function")
print(f"  Cell {insert_position+4}: evaluate_model function")
print(f"\nTotal cells: {len(nb['cells'])}")
print("\nNotebook is now ready to execute!")
